### ISSUE TITLE
After editing exercise selection of current mesocycle, old exercises still retained

### ISSUE THREAD

**Issue by Testah2024** [WhyAsh5114/MyFit#10]
If I have made a mesocycle, start it, then a week later change some of the exercise selections by editing the mesocycle, it MyFit supposed to use the newly edited in exercise selections or is it intentional that it retains the old version of the mesocycle?

For example,
For Monday I changed Cable Side Laterals to Cable Crossover Lateral Raises. But when week 2 started, it still had Cable Side Laterals, rather than the Cable Crossover Lateral Raises I changed it to in the previous week..

**Comment by WhyAsh5114** [comment]
Ah, the workouts copy exercises from the mesocycle only for the first week (cycle 1). 

After the first week, the exercises and their reps, loads, and RIRs are copied from the previous week. 

If you want to make changes which persist in the next workouts, you can edit the exercises in the new workout directly, they'll get copied in the upcoming week.

I know the UI isn't super clear about this, I'll improve it in v3.

**Comment by Testah2024** [comment]
Got it.
I intuitively thought that editing exercises in the workout directly was temporary (ie; you go to the gym, someone is on the machine you want to use, so rather than waiting you replace the exercise for that week only) whereas editing the mesocycle was a permanent change to the entire structure/exercise selecting of the current mesocycle.

If I add or remove exercises in the new workout, will that carry over to the following week (eg; My front delts are already fatigued after several chest exercises, so I take out any direct front delt work for that day, but the next week my front delts are fine to do direct work, wondering if I would I have to manually add them back in again)

**Comment by WhyAsh5114** [comment]
> If I add or remove exercises in the new workout, will that carry over to the following week (eg; My front delts are already fatigued after several chest exercises, so I take out any direct front delt work for that day, but the next week my front delts are fine to do direct work, wondering if I would I have to manually add them back in again)

Yes, all changes to a workout will be transferred to the upcoming weeks, you can re-add your front delt work if you feel like it in the next week, and even that change will carry over to the next-to-next week
