### ISSUE TITLE
SSO for Google currently shows an error

### ISSUE THREAD

**Issue by xenogerm** [WhyAsh5114/MyFit#103]
## Describe the bug

Upon clicking 'Login' and selecting 'Google', the user is redirected to path with https://accounts.google.com/ and OAuth error.

## To Reproduce

1. Click on 'Sign in'
2. Click 'Google'.
3. Review error

## Expected behavior

Sign in should allow the user to login using Google SSO

## Screenshots

<img width="955" alt="image" src="https://github.com/user-attachments/assets/c3892182-b0e6-4e80-a078-7ed44bc9e301">

## Desktop (please complete the following information):

- OS: MacOS
- Browser chrome
- Version ??

## Additional context

Github is also broken. It's likely that credentials have not been created yet for this application.

**Comment by WhyAsh5114** [comment]
Is this in v3 (my-fit-v3.vercel.app) or v2 (my-fit-whyash5114.vercel.app)?

I checked both and they were working for me. Did you clone the project locally? If so, you need to initialise the .env file (see sample.env) with the appropriate client key and secret.

**Comment by xenogerm** [comment]
Yes, I am reproducing the issue locally. It does seem fine in your v2 that I tested.

There is some ambiguity in the required credentials for the .env. Are there application client credentials for a test environment, or should the developers create their own set of credentials? Maybe it could be included as part of the readme since it's a little ambiguous. 

```
AUTH_SECRET="xxxxxxxx"

AUTH_GITHUB_ID="xxxxxx"
AUTH_GITHUB_SECRET="xxxxxx"

AUTH_GOOGLE_ID="xxxxxx"
AUTH_GOOGLE_SECRET="xxxxxx"
```

**Comment by WhyAsh5114** [comment]
Oh, I'll add more details to this file by the end of the day. 

It should also be possible to create a user without needing these credentials as it's a hassle for each developer, I'll probably add a user creation script as well.

**Comment by WhyAsh5114** [comment]
Added some more data in `sample.env` on the `main` branch, let me know if you need anything else :)

**Comment by xenogerm** [comment]
Thank you! Perfect!
