### ISSUE TITLE
Recomended Reps = 0?

### ISSUE THREAD

**Issue by RhinoRSA** [WhyAsh5114/MyFit#106]
## Describe the bug

Algorith decreases reps below minimum.

## To Reproduce

Start with 5 reps - 40 Weight - 3 RIR and just keep logging workouts decrease RIR obviously as the next week you will obviously increase intensity, this should result in the above mentioned case.

## Expected behavior

Decrease Weight not Reps (As the expected rep range was 3-5) if difficulty is too high, 0 RIR should be considered failure, or decrease reps to minimum input, then decrease weight incrementally to either previous value or by percentage increased from previous workout until stability is reached where progression can start applying again.

## Screenshots

![image](https://github.com/user-attachments/assets/465a4ced-9e87-4244-ac72-c171b0aead9d)

## Desktop (please complete the following information):

- OS: Windows 11
- Browser Edge
- Version 129.0.2792.79 (Official build) (64-bit)

## Additional context

Trying to build out the following Program from Jeff Nippard - The Ultimate Push Pull Legs System 6X, but having quite some difficulty.
![image](https://github.com/user-attachments/assets/b2657ca7-dede-40d8-a4a1-d29218b6d661)

**Comment by WhyAsh5114** [comment]
Thanks for the issue submission! 

I'm working on this right now, by replacing the current algorithm with a better one and setting the lower rep range as a hard limit and the higher one as a soft limit to prevent such issues from occurring. See more in #84.

Also thanks for giving the sample program, I'll add them as tests to prevent such issues from occurring in the future.

**Comment by RhinoRSA** [comment]
Thank You!

I might have another suggestion, Currently we can't set the number of sets individually when creating a program whereas on V2 we can, Would also be nice if we could set the starting weight (Side Note: have a check box labeled "warmup sets" then let us decide the qty of warmup sets and the app will divide our suggested/current starting weight into the 3 or 4 warmup sets and also automatically adjust the warmup weight per set as we progress ) so that when we finish a mesocycle, maybe take a week off/deload, we come back and can have a look at where we left off if we decide to run the same program again the previous training weight is either easily put in by the user or automatically populated.
