### ISSUE TITLE
Error 504 This Serverless Function has timed out. 

### ISSUE THREAD

**Issue by aarow7** [WhyAsh5114/MyFit#14]
I'm getting a 504 on multiple devices; the Home screen loads, but essentially everything else is inaccessible.

````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
This Serverless Function has timed out.

Your connection is working correctly.

Vercel is working correctly.

504: GATEWAY_TIMEOUT Code: FUNCTION_INVOCATION_TIMEOUT ID: cle1::5mb7h-1706198334761-3b543dc00ca4

If you are a visitor, contact the website owner or try again later.
If you are the owner, [learn how to fix the error](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_TIMEOUT) and [check the logs](https://my-fit-whyash5114.vercel.app/_logs?requestId=cle1::5mb7h-1706198334761-3b543dc00ca4).

**Comment by WhyAsh5114** [comment]
I tried replicating this on my side, but couldn't do so. Could you send me your split too?

When I checked the logs it showed errors on the `/workouts/new` page, try the other pages such as `/mesocycles` and `/workouts` too.

**Comment by aarow7** [comment]
Privacy Policy is working, /mesocycles is working now-- I was able to fully create a test meso. /workouts is showing history properly and editing is working now. The issue appears to be specific to /workouts/new

Tested in Firefox v122.0 and iOS Safari.

**Comment by WhyAsh5114** [comment]
yeah, I'll need your split then, there's probably an API endpoint or server error. I need to know from what it's being caused.
Send me a screenshot of your mesocycle's workout days so I can repro the error locally.

**Comment by aarow7** [comment]
Here's all the meso settings & days

![IMG_3095](https://github.com/WhyAsh5114/MyFit/assets/3732045/f05fccc0-5206-4452-acc4-fd7ae7fb0041)
![IMG_3096](https://github.com/WhyAsh5114/MyFit/assets/3732045/834a30c2-4414-4f52-ad0b-42c2d0c106ed)
![IMG_3097](https://github.com/WhyAsh5114/MyFit/assets/3732045/030b7488-3547-4caa-9654-2dfd93fa77cb)
![IMG_3098](https://github.com/WhyAsh5114/MyFit/assets/3732045/5f5e1df0-0250-429f-9e59-2b4b359bf5c4)
![IMG_3099](https://github.com/WhyAsh5114/MyFit/assets/3732045/0d092c76-2005-4a4a-bb62-a948f01f6a52)
![IMG_3100](https://github.com/WhyAsh5114/MyFit/assets/3732045/b0f8b0fd-10df-420b-847c-6d2570bb3ab0)
![IMG_3101](https://github.com/WhyAsh5114/MyFit/assets/3732045/590ae631-2182-4aed-8aa6-3fe1de687060)
![IMG_3102](https://github.com/WhyAsh5114/MyFit/assets/3732045/da5e3d3d-3bb4-474f-ad89-64daa2b6f618)
![IMG_3103](https://github.com/WhyAsh5114/MyFit/assets/3732045/e2f9b273-6e74-49ef-ac4b-f0df3c4f4241)
![IMG_3104](https://github.com/WhyAsh5114/MyFit/assets/3732045/85f52db2-81e9-44a4-8b42-2e536dfd9d3d)
![IMG_3105](https://github.com/WhyAsh5114/MyFit/assets/3732045/be1c9dcb-9751-43bd-9d9b-12ffe80668ae)
![IMG_3106](https://github.com/WhyAsh5114/MyFit/assets/3732045/644e8c85-d844-495c-ade7-a96e6d16be3c)
![IMG_3107](https://github.com/WhyAsh5114/MyFit/assets/3732045/a771f23a-8193-4d52-8fbb-1ec24c92d174)
![IMG_3108](https://github.com/WhyAsh5114/MyFit/assets/3732045/ac440bf5-e438-49a4-ab57-67ec9ad992f3)
![IMG_3109](https://github.com/WhyAsh5114/MyFit/assets/3732045/80021584-8409-468d-8b0f-dcf8690f94f7)
![IMG_3094](https://github.com/WhyAsh5114/MyFit/assets/3732045/db48fe2d-eb4b-4092-86dc-197c4effacde)

**Comment by WhyAsh5114** [comment]
I made an exact copy of the split, with a new account, still couldn't repro. Do you have slow internet? Vercel limits functions to only 10s of runtime. That could be a possible reason

**Comment by aarow7** [comment]
Currently getting ~100 megabits down currently, speed is usually not a problem on my end. I’ll check again in a few hours and see if the error is still happening.On Jan 25, 2024, at 10:26 AM, Yash Kolekar ***@***.***> wrote:﻿
yeah, I'll need your split then, there's probably an API endpoint or server error. I need to know from what it's being caused.
Send me a screenshot of your mesocycle's workout days so I can repro the error locally.

**Comment by WhyAsh5114** [comment]
Fixed it (I hope), infinite looping in the progressive overload function, confirm on your side too.

**Comment by aarow7** [comment]
Fixed! Thank you!
