### ISSUE TITLE
Save button stuck buffering on mobile and pc

### ISSUE THREAD

**Issue by Rishi-Ruia** [WhyAsh5114/MyFit#142]
## sometimes when I try to save a workout log on the mobile app and even the pc, the app is stuck buffering on save, refreshing resets the buffer but, when save is pressed again the app still buffers

This issue seems to commonly happen when i change an exercise within the context of an active meso, or sets were skipped during the last iteration of this day.

**Comment by WhyAsh5114** [comment]
I'll need a bit more details, send me your workout in normal and compare mode and I'll try to debug it.

**Comment by Rishi-Ruia** [comment]
example of a workout i did today, i had to skip last weeks version of today

![Screenshot 2024-11-08 211613](https://github.com/user-attachments/assets/433861ab-db15-4185-8db4-8c9506174b82)
![Screenshot 2024-11-08 211452](https://github.com/user-attachments/assets/c29d02c7-f755-4a06-bb96-69d4a0f20d0e)

**Comment by Rishi-Ruia** [comment]
![image](https://github.com/user-attachments/assets/871cfb42-9d85-4825-9ffd-6bbfa8fd85b3)
![image](https://github.com/user-attachments/assets/5c56a805-17ac-4099-adb7-13f9aff1a9d1)
![image](https://github.com/user-attachments/assets/426e49e8-0e3b-4186-9538-69ed6facc986)

**Comment by WhyAsh5114** [comment]
I'll look into this in a few days, I am currently a bit busy with some other things.

**Comment by Rishi-Ruia** [comment]
*quick update* after testing it appears the issue is caused by manually adding and subtracting more sets, im not exactually sure the exact cause but after constantly trying new combinations of adding and removing sets, then deleting the day I was able to save my original workout

**Comment by Yun5Pc** [comment]
have been having this problem for a while. the workaround ive found is to just fill in the sets as is, save, and then go to the workouts tab and edit your workout there to add or substract your sets/load/rir

**Comment by WhyAsh5114** [comment]
The issue was in the myorep match's load handling, it should be fixed now.

If you encounter such errors again, feel free to re-open it.
