### ISSUE TITLE
Suggestion Myorep match Downsets

### ISSUE THREAD

**Issue by Yun5Pc** [WhyAsh5114/MyFit#144]
would it be possible to add myorep match downsets?
with just normal myorep match the amount of sets you can do with a specific load is limited for example i do myorep match on pushdowns between 10-20 reps on my 5th set my reps on the initial set drops to below 5 which would mean i have to switch to a different excercise

**Comment by WhyAsh5114** [comment]
That's definitely a valid use case. Will add it soon.

**Comment by Yun5Pc** [comment]
Appreciate the awesome work man keep it up
