### ISSUE TITLE
View the history of a excercise

### ISSUE THREAD

**Issue by Yun5Pc** [WhyAsh5114/MyFit#150]
## Is your feature request related to a problem? Please describe.

currently the only way to view the history of a specific excercise is to start your current workout and tap the three lines and open history

## Describe the solution you'd like

how about adding an option in the workout logs in the workout tab as well

## Additional context
correct me if ive missed anything about the history thing

**Comment by WhyAsh5114** [comment]
Yeah, this is something I want to implement as well, I mentioned it in issue #140 

It's just that I'm a bit busy with exams this month. Once they're over, I'll start working on this.

**Comment by Yun5Pc** [comment]
aah my bad if i seemed rude or smth
i didnt see the issue #140
gl with ur exams

**Comment by WhyAsh5114** [comment]
Npnp, u mentioning the same helps me prioritise it. I was gonna pick any of the open issues but now I'm more inclined to pick this one.

Thanks for the well wishes!
