### ISSUE TITLE
A way to add feedback

### ISSUE THREAD

**Issue by Yun5Pc** [WhyAsh5114/MyFit#156]
## Is your feature request related to a problem? Please describe.

Since the feedback options on the v2 is not available in v3 i think there is no way to add feedback or comments about a workout anymore 
for example writing down a reason for messing with the volume, adding a comment about how your form improved,how the workout felt or maybe u did a deload session due to feeling sick etc
        
## Describe the solution you'd like

So for now i think it would help addng a way to add notes for a workout and make it visible under the basics tab on a logged workout
this dosent restrict you to limited options as before you could only remark about the pump joints and intensity giving you alot of freedom for users

## Additional context

feel free to discuss if u have anything in mind about this

**Comment by WhyAsh5114** [comment]
Umm, are the individual notes for each exercise in a workout not enough for that?
![image](https://github.com/user-attachments/assets/7eb3a0e1-1a6b-4144-8d6f-b322e22d7eda)
![image](https://github.com/user-attachments/assets/bdcc7c03-e63e-4b99-9de2-02eb51774b32)

**Comment by Yun5Pc** [comment]
my bad if i was being rude i just tested this 
because the notes 'behind the back, strict' showed up in every following workout i assumed changing it would change it in my previously logged workouts as well that seems not to be the case which is very nice
but another thing is from my perspective it is actually beneficial to add btb or strict into the actual exercise name because it makes it easier to distinguish between them 
for example in the new exercise stats tab if i named my exercise cable lateral raise i wouldnt be able to isolate specific variants of lateral raises like the btb or seated to see how ive progressed in those specific variants of course this probably is due to the excercise stats tab being not fully finished
even before the exercise stats page i found my self doing this because it seemed more efficient in the long run

so though the problem itself is technically fixed by being able to use it like this
![image](https://github.com/user-attachments/assets/37908299-5d76-40cb-85fe-fb1c2147ac54)
i still think being able to add a note for your workout as a whole would improve the app
![image](https://github.com/user-attachments/assets/dad70db1-5554-4736-9130-bc62ed170712)
and it can be used to fill the empty space under the basics tab as well

lemme know what you think about  that
i do apologize if im being a bother bro feels like im arguing lol

**Comment by WhyAsh5114** [comment]
Bro chill. You are being polite and its a fair request, I myself have thought about adding this. I will add it in the next update, dw.

**Comment by Yun5Pc** [comment]
damn that was fast lol pretty awesome as always appreciate the hard work keep it up man
i do have some more quick questions and issues i wanna talk about 
first of all would you mind explaining me how the relative overload function works
and a lil qol improvement would be adding the workout date for the workouts so its easier to identify them with the graph
![image](https://github.com/user-attachments/assets/225e529b-58cd-4450-843f-5854a4ce9d44)

and lastly ive run into a problem where there are duplicates in my excercise stats tab 
when i select the first one the second one gets highlighted and vice versa it seems like they are both the same entry but have 2 instead of one can u help me out with that
![image](https://github.com/user-attachments/assets/54c6bfe9-87dd-41ed-801f-7721f4399e96)

**Comment by WhyAsh5114** [comment]
Okay, I'm not sure if the double entry bug will be fixed but I've implemented proper filtering there, try it out and lmk

**Comment by Yun5Pc** [comment]
yup the bug hasn't still been fixed
i think it might be due to me creating 2 exercise splits in v2 using the same name it probably got recognized as two diff exercises back then
would that help you find out the root cause

and btw im still puzzled about the relative overload chart ive tried working it out how its calculated and stuff im just clueless lol

**Comment by WhyAsh5114** [comment]
Hmm, I can't really reproduce that bug on my side, make sure you refresh and update the app. And after that try clicking on both of them, and tell me if the results are the same.

The relative overload chart uses Berger's formula (#84), on your very first exercise performance and compares your subsequent performances to get an overload percentage, it considers both reps and load. You can also just use the Absolute load option if you want to see only load change over time.

**Comment by Yun5Pc** [comment]
okay so i was just about to give up cuz i thought no new users will prolly run into this issue but ithink i found what the cause is it seems that one of the exercise names have a space at the end
can confirm this on my other duplicates as well
![image](https://github.com/user-attachments/assets/81bbc7a2-e345-45e2-bd3a-33e407b37df1)
![image](https://github.com/user-attachments/assets/dab29999-7c86-4d5d-8729-08441c0e4c85)
but i do wonder why it highlights both entries when hovering over just one

is there a way that i could combine these two entries by renaming one of the exercises perhaps
and btw now the overload chart makes alot of sense thx for the help bud

**Comment by WhyAsh5114** [comment]
I'll look into something for renaming, #160

**Comment by Yun5Pc** [comment]
awesome

**Comment by Yun5Pc** [comment]
something ive just tested now is whether i could add notes to already logged workouts
while i can go back edit the workout and put a note in
the notes do not show under the basics tab in already logged workouts

**Comment by Yun5Pc** [comment]
Awesome stuff man keep it up ill let you know if i run into any issues while testing

**Comment by Yun5Pc** [comment]
a lil more feed back on this 
when you edit a previously logged workout that already has a note
![image](https://github.com/user-attachments/assets/bfa78c62-27df-4f67-9ff5-abad2ffe39f8)

the note is deleted
![image](https://github.com/user-attachments/assets/36dd345c-74ff-4c5a-a0b7-f18185b48e72)

i think it would be better to somehow keep the previous note there so you can edit it instead of having to write it all over again

this also prevents you from accidently deleting the note when u go back to only edit something like load/rir/reps and hitting save without knowing the note was deleted
