### ISSUE TITLE
Swapping between workouts 

### ISSUE THREAD

**Issue by Rjc1999** [WhyAsh5114/MyFit#16]
Hi thank you so much for developing this app

I just had an issue today where I wanted to add an exercise to a completed work out done as a seperate session but on the same day and I had to cycle through all my workouts for the week to get back to the proper workout for the day

Would it be possible to add exercises to completed workouts and to scroll through different workouts on the day you'd like to train on?

**Comment by WhyAsh5114** [comment]
Oh damn, sorry i forgot to add the add exercise button when editing (updating) a workout, I'll do that by tomorrow.

As for the cycling through thing, I don't think that'll be necessary if you're able to add exercises to already performed workouts right?

**Comment by Rjc1999** [comment]
Yes likely I won't ever want to cycle through the exercises again if the app starts me on the proper work out for the day
