### ISSUE TITLE
Can't find "install app" button and constant sign outs

### ISSUE THREAD

**Issue by Testah2024** [WhyAsh5114/MyFit#19]
Hi,
I recommended my friend to try out MyFit, their first day today, but they showed me there is no install button to add to home screen, and they're constantly being signed out every 15 minutes or so.

Any idea how to solve this?
iOS using safari. 

Thanks

**Comment by WhyAsh5114** [comment]
Safari on iOS doesn't have as good of an implementation of the PWA spec as most other platforms. It is doable but in a different way: https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DiOS

Tell your friend to try the above method and see if the login issue persists. Also thanks a lot for sharing the app with your friend :)

**Comment by WhyAsh5114** [comment]
did this get fixed?

**Comment by Testah2024** [comment]
They are stubborn about using Safari, so they just favourited it on Safarai

The login issues stopped thankfully.

**Comment by WhyAsh5114** [comment]
Closing as I personally can't do anything for [PWA on iOS](https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DiOS) and the sign-outs issue is fixed. 
Without Chrome, I doubt they can get to install the app for a native feel.
