### ISSUE TITLE
Every workout is incorrectly read.

### ISSUE THREAD

**Issue by Cactuxfrombrazil** [WhyAsh5114/MyFit#27]
Every day where I go to start a new workout, I click the "Upcoming Workout" on the home page, then "Log workout".
as an example, Let's say I'm workout number 3. when I click in Log Workout, and it redirects me to the page where I can log my reps, weight etc, it always reads the exercises from workout number 2.

To fix this, I have to go back to the home page, click on the upcoming workout again, then "overwrite workout" then it reads the exercises correctly.

**Comment by Testah2024** [comment]
Common issue, I get the same thing.
