### ISSUE TITLE
Mesocycle Deleted

### ISSUE THREAD

**Issue by EliavRevah** [WhyAsh5114/MyFit#3]
A mesocycle I created has been deleted after updating, is it a result of the update? Or is it a bug?
On top of that before the update I could have seen my weekly stats.
Where can I find those?

**Comment by WhyAsh5114** [comment]
Sorry for the trouble, I didn't really expect for the project to have any active users 😅
I'll create another deployment in vercel for v1, you can view your old mesocycles and workouts over there.

**Comment by WhyAsh5114** [comment]
Here's the v1 deployment URL: https://my-fit-v1.vercel.app

I don't have any plans for creating a complete migration from v1 to v2 for now, that would be a lot of effort.
If a lot of people want it, I might get to it.

v2 is also still incomplete, the mesocycle charts, progression algorithm, are still in the works. I'll finish that this month itself.
