### ISSUE TITLE
Suggestion: Set Types

### ISSUE THREAD

**Issue by Cactuxfrombrazil** [WhyAsh5114/MyFit#31]
Add an option for Supersets, Myo rep/Myo rep matching sets, Giant sets and Dropsets

**Comment by WhyAsh5114** [comment]
Yep, a planned feature for v3, mentioned in #6

**Comment by iamjexcdevvv** [comment]
> Yep, a planned feature for v3, mentioned in #6

Anyway is there also warmup set? many of us will really benefit from it

**Comment by WhyAsh5114** [comment]
Yep, mentioned in #7, this is also something I'm planning not to save in the database but have an option for it just for user convenience's sake
