### ISSUE TITLE
unlimited loading when mesocycle finished

### ISSUE THREAD

**Issue by Ankilli** [WhyAsh5114/MyFit#36]
Hey there, thanks for this awesome app!❤️

I just completed a mesocycle and marked rest days as completed as well, like usual.
When I now advance to log the next workout (assuming it's a first deload?) the screen stays black and it's loading forever (moving circle in top right corner). When I try to reload the page it just says 500 internal error.
The same happens when I open it in the browser.
Then I can't go to any other page from the drop down menu, have to close the app for that :(

![IMG_20240525_071323](https://github.com/WhyAsh5114/MyFit/assets/89978096/cc45f041-e4f6-480d-931a-ccd073d71fd5)

Regards, and again: awesome app 😎

**Comment by Ankilli** [comment]
Ah nvm, just read about the 'Automatic deload creator' feature in the v3 blog post. Then I know I can just stop the mesocycle myself :)

**Comment by WhyAsh5114** [comment]
ah, sorry for the false advertising of v2 😅
