### ISSUE TITLE
Muscle list

### ISSUE THREAD

**Issue by Propanotrio1** [WhyAsh5114/MyFit#37]
First of all, great job you are doing here. I hope I can help with suggestions. 

Y created a mesocycle and I started listing exercices and what I observe is the need of some additional muscles in the list:
- Abductors
- Adductors
- Soleus 

Keep it up!!

**Comment by asherrrrrrrrrrr** [comment]
and neck please!

**Comment by WhyAsh5114** [comment]
Hey guys, thanks for the suggestions, but I need a bit more clarity in this, the neck can be added easily as it's a completely different muscle group. Even adductors and abductors are actually separate from the quads anatomically. But here's the issue:

### Some muscles are commonly trained with other major muscle groups
Muscles like the soleus are always trained in standing variations of the calf raises, they can be specifically targeted slightly more in seated variations but it doesn't increase their activation as much AFAIK.

Another example for this is rhomboids, which are commonly trained during rows, which most people consider as a upper back or rather trap-dominant exercise. If we separate the muscles as much as we can for the sake of accuracy, it makes it a bit confusing for beginners and even for us who know anatomy well enough as what we should select for an exercise which targets multiple muscle groups. 

I am still open to feedback in this part.

### If we separate major muscle groups, we need to do it for all groups
Even if we do separate the calves muscle group into the gastrocnemius and soleus, we need to do so for others as well: like the chest being split up into upper and middle, the triceps being split into either all the 3 heads, or the (lateral+medial) head and long head according to the function. It makes the list a bit inconsistent.

There are a few options to fix them though, one is where we have multiple lists with different levels of detail, like a general one which we use now, and a more sophisticated one with as much separation as possible, its a great idea for sure, but we need to make this a bit more consistent so users don't get confused. Would appreciate any ideas you guys have in mind :)

**Comment by Propanotrio1** [comment]
I agree with all what you said. The thing is that you are forced to chose a muscle, and for abductors and adductors I put them with hamstring exercises. 

Indeed, too much resolution is not needed, and a list of main muscles is enough :)

**Comment by WhyAsh5114** [comment]
so we should keep it as is? (along with neck)

**Comment by asherrrrrrrrrrr** [comment]
I agree. I put abductors with glutes and adductors with quads. Maybe you could add an option for a custom muscle for those who care to be specific although not nessary.

**Comment by asherrrrrrrrrrr** [comment]
> so we should keep it as is? (along with neck)

I'd appreciate if you can add neck please

**Comment by WhyAsh5114** [comment]
> > so we should keep it as is? (along with neck)
> 
> I'd appreciate if you can add neck please

done, added neck muscle group!

**Comment by Propanotrio1** [comment]
_

> Maybe you could add an option for a custom muscle for those who care to be specific although not nessary

_ 

It is a good option, without adding too much resolution for new users or beginners.

**Comment by WhyAsh5114** [comment]
> It is a good option, without adding too much resolution for new users or beginners.

Got it, I'll add the custom one in v3 of the app, if you want I could add adductors and abductors right now in v2 as they are actually different from the quadriceps and can be specifically targeted which might make sense for some users. Do let me know if you want it.

**Comment by Propanotrio1** [comment]
If it doesn't take you that much time, It would be grateful 💯 
I will start using the app tomorrow at the gym (replacing my old Excel), really excited

**Comment by WhyAsh5114** [comment]
Done! Hey, even I used to use Excel for my workouts, part of my motivation for this app was to get away from Excel 😁. Good luck with your sessions!

**Comment by asherrrrrrrrrrr** [comment]
> > > so we should keep it as is? (along with neck)
> > 
> > 
> > I'd appreciate if you can add neck please
> 
> done, added neck muscle group!

Great thank you!
