### ISSUE TITLE
mesocycles

### ISSUE THREAD

**Issue by asherrrrrrrrrrr** [WhyAsh5114/MyFit#38]
I'm not sure if this has been addressed already but can you make it so that you can change someontning in a mesocycle without it getting rid of all of the previous workout data?

thank you!

**Comment by WhyAsh5114** [comment]
I think you probably can, but what exactly did you want to change?

**Comment by asherrrrrrrrrrr** [comment]
sometimes I replace exercises or change the order of exercises and the data
of all the exercises goes.

**Comment by WhyAsh5114** [comment]
I see, changing exercise names will cause data loss during the first week of the mesocycle, but from the second week onwards data from the mesocycle exercise split isn't taken anyways, the app uses the previous week for the new data. 

Changing the split schedule order can indeed cause data loss as the app now has no idea how the current split relates to the old one so it just starts from blank.

But even if u do make any changes (aside from the split day names and schedule), only the first week should be affected which starts from blank regardless, and second week utilizes this first week.

**Comment by asherrrrrrrrrrr** [comment]
I see! Would it be possible to implement a feature where all exercises are
listed in a dedicated section? This would allow users to manage their
exercises more effectively. Specifically, when adding an exercise to a
mesocycle, users could choose whether the performance data (such as weight
and reps) should be taken from the last time the exercise was performed in
general or the last time it was performed within the current mesocycle.

This feature would be particularly useful when changes are made to a
mesocycle. Currently, modifying one day can affect all other days, which
can be inconvenient when it comes to tracking weight and reps. Having the
option to reset or retain data based on the context (general history vs.
mesocycle-specific) would provide greater flexibility and accuracy in
tracking progress.

**Comment by WhyAsh5114** [comment]
Ahhh, that's a great idea! A dedicated section for managing the current exercises of the mesocycle! But it's a really big feature though, so I'll implement it in v3, my exams will be over very soon, so I'll be working on it ASAP.

**Comment by asherrrrrrrrrrr** [comment]
Yes of the mesocycle or just in general. Thank you! Best of luck on your exams! 🤞🏼

**Comment by WhyAsh5114** [comment]
Thanks man :)

**Comment by asherrrrrrrrrrr** [comment]
ofc!

**Comment by yzee-tech** [comment]
> Thanks man :)

Hey, just wanted to comment that I really like your app. I agree with the suggestion here if its possible to standardize exercises. Personally I often don't get to always use the same gym,  and need to substitute exercises if certain machines aren't available. It Would be great to be able to keep the progression data going in those instances.

**Comment by WhyAsh5114** [comment]
@yzee-tech Got it, substituting exercises is an important consideration. For your use case it'd make sense to swap out exercises and load their rep numbers from the latest possible workouts right?

**Comment by yzee-tech** [comment]
> @yzee-tech Got it, substituting exercises is an important consideration. For your use case it'd make sense to swap out exercises and load their rep numbers from the latest possible workouts right?

Yes exactly. So for a given day, maybe there's a machine chest-fly exercise scheduled, but if someone's not at their usual gym, maybe they need to substitute with dumbbell bench chest-fly, or incline chest press, so it would be good to load the rep from the most recent workout with that exercise. I imagine upfront, it would require a bit more setup, because maybe the user would need to create all the exercises first so that they can be in some kind of reference list, and then choose them to put into a mesocycle?

**Comment by WhyAsh5114** [comment]
Yeah... the implementation of this is quite big, but its something I'll definitely add in v3, where you could swap out an exercise for another one and it'd get the latest rep numbers in that mesocycle.

The pre exercise creation is there in v3 but I am planning to use it for a different reason, we typically start with low volumes and gradually progress, so at the start we don't need many exercises. I made the pre exercise creation feature to facilitate this particular need. Exercise swapping would be better implemented as an optional feature where you can change exercises on-the-go in the workout itself.

**Comment by yzee-tech** [comment]
@WhyAsh5114 when are you targeting for V3 to be released?

**Comment by WhyAsh5114** [comment]
@yzee-tech I've created a GitHub discussion to keep you all updated on the progress of v3: https://github.com/WhyAsh5114/MyFit/discussions/45
