### ISSUE TITLE
Volume progression per between sessions

### ISSUE THREAD

**Issue by Propanotrio1** [WhyAsh5114/MyFit#39]
Hi there, 

I have a suggestion for the Volume progression plots. In my personal case I have a 4-day split with 2 upper body and 2 lower body sessions during the week. The plots of my progression use both "type" of sessions (the red curve connects the volume of all 4 sessions). For me, it would make more sens to have different plots for my volume progression, one plot following the upper body, and one plot following the lower body. 

Thank you for your work, and keep it up :)

Yesterday I tried it for the first time and yea, it is demanding!

**Comment by WhyAsh5114** [comment]
ah ok, a filter to see individual days right? that seems basic enough so I guess I'll add it in v2.
But u said u have a 4 day split, so do you want a multiple select in which u can select both of ur upper days or both of ur lower days to see their volumes?

**Comment by WhyAsh5114** [comment]
ohk, I misunderstood the first time, using separate plots doesn't seem ideal to me as they typically mean tracking different types of data, which is why I used bar for sets line for volume. Something better would be using different colours to track the different workout types throughout the week, like red bars with red lines for ur day1

**Comment by WhyAsh5114** [comment]
I have added separate volume tracking for each workout type, re-open the issue if you feel there should be something else, but understand that I won't be able to implement big tracking stuff right now as I'm mostly focusing on v3, and juggling between the two is really confusing as the underlying tech and terminologies are quite different now
