### ISSUE TITLE
Can't create a new mesocycle 

### ISSUE THREAD

**Issue by EliavRevah** [WhyAsh5114/MyFit#4]
In the 3 step for creating a mesocycle after moving from one day to the other the exercises get deleted.
Also if you refresh the days also reset showing nothing but empty white boxes.
On top of that there is no edit button for previously created mesocycles.

Thank you and have a nice day☺️

**Comment by WhyAsh5114** [comment]
fixed the mesocycle creation bugs, working on the edit mesocycle feature for now

**Comment by WhyAsh5114** [comment]
added edit mesocycle feature
