### ISSUE TITLE
how do i actually download this onto a phone or computer

### ISSUE THREAD

**Issue by Bunkyyy** [WhyAsh5114/MyFit#40]
sorry if this seems basic or a waste of time, im not very good with all this coding stuff and github but i found this app and i wanna try and and download it onto my computer and or phone. Problem i have with this is i dont know what to do, like theres the 4 steps in the description but i have no idea what to do with them. I have installed Node.js and then tried to do the git clone thing in the node.js prompt but it doesnt work. I also tried with powershell and that didnt work saying something about not recognizing 'git'. Im just really stuck and if its possible would like some help installing this, if it is even available. Thank you

**Comment by WhyAsh5114** [comment]
Hey there, just visit the website link, it's a web app and shows a download icon after loading. 
https://my-fit-whyash5114.vercel.app/

It's a PWA and by simply opening the site you can download it on PC or Android, you don't need to clone the app on your local device if you don't want to.
