### ISSUE TITLE
App is completely broken

### ISSUE THREAD

**Issue by ChewieGumm** [WhyAsh5114/MyFit#48]
Not a very tech savy guy so might be missing something here but when I try to get to the app via the link :https://my-fit-whyash5114.vercel.app/ it just completely broken, and I'm unable to actually interact with anything on the website like my workouts e.t.c without being met with a "not found" error on a blank page. I've also tried this link (https://my-fit-jgqg-iirdrn1ef-whyash5114s-projects.vercel.app/) since it was the only other thing here that just looked like the app before (other than the preview) but when I try to login w/ google it just states my request was invalid
![image](https://github.com/user-attachments/assets/3fb1e8c7-8421-46eb-abcb-b8ffb389d5cf)
![image](https://github.com/user-attachments/assets/9b71e955-d332-4d17-b700-d80a3f8b8fb6)
![image](https://github.com/user-attachments/assets/47c0ceea-49ae-45f1-a354-edac67aab4da)

**Comment by ChewieGumm** [comment]
K nvm just switched networks and now its working? not quite sure whats wrong with my wifi but oh well its working

**Comment by Testah2024** [comment]
You should have left this open.
I'm now having the same issue, so its not something specific to you.

**Comment by WhyAsh5114** [comment]
Hmm, it's working for me though right now, on various devices. Nothing weird in the logs too.

I did merge a PR in the master branch yesterday so maybe that has caused some invalidation issue with the service worker. Try to reinstall the app or clear its cache and data.

**Comment by Testah2024** [comment]
> I did merge a PR in the master branch yesterday so maybe that has caused some invalidation issue with the service worker. Try to reinstall the app or clear its cache and data.

Whenever I am using a wifi connection on mobile specifically, I got a blank page with "Not found" written in the left corner whenever clicking on Mesocycles or Workouts. But clicking Privacy Policy and V3 Blog work as normal. Using a PC to access using the same wifi connection, everything works normally. Using a phone with mobile data and wifi turned off, everything works normally.

After clearing cache on the phone, now suddenly when I attempt to go to the link for the app it states:
 "You connection is not private. Attackers might be trying to steal your information.
 NET: ERR_CERT_COMMON_NAME_INVALID"
