### ISSUE TITLE
Allow for deletion of workouts, after deleting the meso linked to those workouts. 

### ISSUE THREAD

**Issue by Dylan-Pettinelli** [WhyAsh5114/MyFit#49]
I was testing how this app works and I skipped ahead a week to see the progression recommendations and afterwards I had a bunch of workouts in the logs that I wanted to delete but I couldn't because I deleted the mesocycle associated with those workouts before trying to delete the workouts. 

In short, it would be great if you could delete workouts even if the mesocycle isn't active or existing. 

Also I love the app, I thought of making this myself because I watch Dr Mike and eventually ran into this haha.

**Comment by WhyAsh5114** [comment]
I think I already fixed this issue, there was someone with a similar problem. Ah my bad, I didn't promote that commit to production. Fixed it.

Hehe, thanks for the kind words. Just curious though, what were you planning to make it with?
