### ISSUE TITLE
New V3 Link showing "redirect_uri" error. Can't login.

### ISSUE THREAD

**Issue by Testah2024** [WhyAsh5114/MyFit#63]
When using the new direct link to V3 (https://my-fit-v3.vercel.app/), upon trying to login, I'm met with an error, as seen in the image below:
![image](https://github.com/user-attachments/assets/348b9e10-e333-42ba-8997-99b0727d8769)

This only occurs when trying to use github to login. Google login works fine.
This happens on both PC and Mobile.

**Comment by WhyAsh5114** [comment]
Ohh, I didn't add the v3 URL to GitHub's OAuth token, my bad. 

Will create one for it in a bit.

**Comment by WhyAsh5114** [comment]
Just updated the URLs, should work now. Feel free to reopen if any issues occur.

**Comment by Testah2024** [comment]
> Just updated the URLs, should work now. Feel free to reopen if any issues occur.

I'm brought to this page:
![image](https://github.com/user-attachments/assets/173ab226-b350-45c3-9f51-76ecf024d6f0)

To which I click to login with github, and was brought to a page for reauthorization, upon clicking to authorize on the following page, I'm circled back to the page in the screenshot above, and when clicking "sign in" again nothing happens.

**Comment by WhyAsh5114** [comment]
It seems like you also logged in with Google, the app currently disallows email linking across different providers due to [security reasons](https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option).

If you want to login with GitHub instead, you can tell me your email address and I'll delete the account from the database, you can then login with GitHub. Or you could just login with your Google account for now.

**Comment by Testah2024** [comment]
> It seems like you also logged in with Google, the app currently disallows email linking across different providers due to [security reasons](https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option).
> 
> If you want to login with GitHub instead, you can tell me your email address and I'll delete the account from the database, you can then login with GitHub. Or you could just login with your Google account for now.

anonanontemp123@gmail.com

**Comment by WhyAsh5114** [comment]
Done, removed the User account, try again now

**Comment by Testah2024** [comment]
Thanks, working now.
