### ISSUE TITLE
"Access Blocked" Google Verification Error

### ISSUE THREAD

**Issue by Testah2024** [WhyAsh5114/MyFit#8]
When trying to open the web app, I'm met with an error stating:
"Access blocked: my-fit-whyash5114.vercel.app has not completed the Google verification process.
my-fit-whyash5114.vercel.app has not completed the Google verification process. The app is currently being tested and can only be accessed by developer-approved testers."

**Comment by WhyAsh5114** [comment]
Hmm, the app was working without verification. Maybe try with a different Google account, if that doesn't work I'll add a GitHub OAuth as well for login.

**Comment by Testah2024** [comment]
I tried 3 different google accounts, both from computer and phone, all unfortunately had the same issue saying "access blocked"

**Comment by WhyAsh5114** [comment]
okay, I have added a GitHub OAuth login as well, try that and let me know if it works.

**Comment by Testah2024** [comment]
Working so far, thanks

**Comment by WhyAsh5114** [comment]
I'll verify the app when I finish working on v3, that is on my TODO list.
