### ISSUE TITLE
"Log Workout" greyed out - Non functioning

### ISSUE THREAD

**Issue by Testah2024** [WhyAsh5114/MyFit#9]
I'm unsure if because this is a work in progress if its intentional that "Log Workout" actually function, or if I'm having some issue?
"Skip" works. "Log Workout" does not.

**Comment by WhyAsh5114** [comment]
It should work though, can you share a screenshot? Maybe you didn't save your bodyweight and there's an exercise for that routine that requires your bodyweight to calculate the volume.

**Comment by Testah2024** [comment]
I can't get through this, not sure what I'm missing. The 

![image](https://github.com/WhyAsh5114/MyFit/assets/155659963/f6541289-a596-4726-acd2-499231624bf8)

**Comment by WhyAsh5114** [comment]
Ok I'll try to fix it by today, send me ur split for Monday, so I can reproduce the bug on my machine

**Comment by Testah2024** [comment]
![image](https://github.com/WhyAsh5114/MyFit/assets/155659963/c453eecb-773a-4a7c-bc70-fd84bae61364)

**Comment by WhyAsh5114** [comment]
I've made a fix, see if it works now?

**Comment by Testah2024** [comment]
Working perfectly so far
