### ISSUE TITLE
V3 Cannot do negative weight?

### ISSUE THREAD

**Issue by Testah2024** [WhyAsh5114/MyFit#91]
It seems when I try to add a negative weight in V3, such as Assisted Pull Ups, it says the number must be greater than 0.
This was working in V2.

Also, just wanted to add instead of opening up a new thread:
In V3, for some reason, despite the rep range being "15-20" its recommending basically doubling the weight and doing 4 reps in the next session or some reason.

**Comment by WhyAsh5114** [comment]
Ohk, the negative weight thing is easy to fix, will do that soon. 

For the rep range issue, I am working on the progression formula currently (#84), but please do create a new issue with attached screenshots for the weird progression.
